name: Cacerola
favicon: null
layout_spectrum: 0.24168
typography_spectrum: 0.8841572692617774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151518'
    - '#b7412a'
    - '#000000'
    - '#800000'
    - '#aa2b2b'
  brandStrength: 0.5
  lightness: 0.8419855430256575
  saturation: 0.1092347011435777
  rhythmicContrast: 0.6376550975255668
purpose: []
