name: Cacerola
favicon: null
layout_spectrum: 0.7777414349839091
typography_spectrum: 0.8841572692617774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.45116287539713085
  lightness: 0.8419855430256575
  saturation: 0.1092347011435777
  rhythmicContrast: 0.6376550975255668
purpose: []
