name: Cacerola
favicon: null
layout_spectrum: 0.24168
typography_spectrum: 0.74853
title: Cacerola Growth Marketing - Valida tus ideas en un corto tiempo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-39073529-11
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151518'
    - '#b7412a'
    - '#000000'
    - '#800000'
    - '#aa2b2b'
  brandStrength: 0.5
  lightness: 0.8419855430256575
  saturation: 0.1092347011435777
  rhythmicContrast: 0.6376550975255668
purpose: []
